### ISSUE TITLE
compleshion.zsh overwrites CDPATH

### ISSUE THREAD

**Issue by ldelossa** [changs/slimzsh#11]
https://github.com/changs/slimzsh/blob/master/completion.zsh#L30

I believe this is stopping me from exporting CDPATH in my .zshrc

**Comment by changs** [comment]
Hi @ldelossa 
I've just removed that line(https://github.com/changs/slimzsh/commit/bee22f58f48503a73f0a1d5579a8ba2be87a4a8a), it was not needed anyway. Thanks for reporting!
