### ISSUE TITLE
Problem with setup prompt_pure_setup:43:

### ISSUE THREAD

**Issue by xhapoo** [changs/slimzsh#13]
Hello,
After setup source `"$HOME/.slimzsh/slim.zsh"` in `~/.zshrc` i got this problem:
`prompt_pure_setup:43: bad set of key/value pairs for associative array`
I have newest iterm2, how can I deal with this?

**Comment by changs** [comment]
Hi, it seems that pure can have some compatibility issues in some rare circumstances. Do you just have slimzsh or do you have any other modifications? 
Please check https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236#gistcomment-2766928 and https://github.com/sindresorhus/pure/issues/327 . Maybe you have a similar problem.

**Comment by changs** [comment]
@shkikato Hey, have you managed to find and fix the problem?

**Comment by shkikato** [comment]
I did not solve the problem, I would rather let it go

**Comment by davep3rrett** [comment]
Hi @changs, I am actually having the same issue:

```
prompt_pure_setup:43: bad set of key/value pairs for associative array
```

when a new terminal session launches.

This is happening with a fresh `.zshrc` containing only the line `source "$HOME/.slimzsh/slim.zsh"`.

I recently uninstalled Oh My Zsh and was hoping to replace it with slimzsh, which I run on my Arch Linux box with no problems.

This is occurring on macOS Sierra 10.12.6, both in the default Terminal.app and in iTerm2 (build 3.2.8).

Any advice or thoughts would be greatly appreciated! Let me know if you need more info about my environment. Thank you!

**Comment by changs** [comment]
Could you also check your zsh version (`zsh --version`)? It seems that you need version newer than zsh 5.6.2.

**Comment by davep3rrett** [comment]
@changs thanks for your response!

I think the zsh version is the culprit:

```
zsh 5.2 (x86_64-apple-darwin16.0)
```

I think this is the default zsh that ships with macOS - I will install a recent version via Homebrew and will confirm if that resolves the issue. Thanks so much!

**Comment by davep3rrett** [comment]
@changs confirming all is working as it should under `zsh 5.7.1 (x86_64-apple-darwin16.7.0)`.

Thanks again!

**Comment by changs** [comment]
Glad to hear that 👍 
@xhapoo you can also check that ^^
