### ISSUE TITLE
Fasd not working as shown in the Readme

### ISSUE THREAD

**Issue by Nacho114** [changs/slimzsh#18]
Hi, 

I installed slimzsh as described in the Readme, then I installed fasd via brew. 

Each works as intended, but when I try to follow the example in the slimzsh, " i.e. Then you'll be able to search inline for the best matching file like here"

vim .slim -> followed by tab should give related documents to complete to.

It however does not seem to work; any ideas, it seems that maybe slim is not recognizing fasd?

I checked and `command -v fasd` is not null, so in `slim.zsh` it should be loaded.

**Comment by changs** [comment]
Hi,

have you used your console for a while after installing fasd?
Fasd (by default) uses your command history (but only after the moment it was installed and initialised) to search for matches. 

FASD readme: 
`When you run fasd init code or source fasd, fasd adds a hook which will be executed whenever you execute a command. The hook will scan your commands' arguments and determine if any of them refer to existing files or directories. If yes, fasd will add them to the database.`

If that helps I'll update the README as in the current form it might be misleading.
