### ISSUE TITLE
Pure Error in git folder

### ISSUE THREAD

**Issue by felixfoertsch** [changs/slimzsh#9]
Hey! Been using slimzsh for a while now. Thanks for this nice program. :-)

I'm getting this error in every git directory now:
prompt_pure_async_callback:13: bad math expression: operand expected at `> 2 '

It's probably linked to this error: https://github.com/sindresorhus/pure/issues/258

The author said it should be already fixed. How can I fix this as well? Do you have to update something in the repo?

EDIT: Never mind, was a problem with my dotfile manager and submodule error. Sorry for the inconvenience.

**Comment by changs** [comment]
Hi. Thanks for the info. I've updated `pure` module. https://github.com/changs/slimzsh/commit/9c27ff2c66a42068dc1762812e0cd12d0d0f6405
